### ISSUE TITLE
Call async freezes on sync flow

### ISSUE THREAD

**Issue by toddpi314** [Bartvds/grunt-execute#6]
When calling 'call' with the async api, sometimes the callback doesn't fire if the actual payload isn't dispatched.

As an example, if we define our payload as:

``` javascript
        callback_async: {
            // function call also supports async callback
            call: function(grunt, options, async){
                // get the callback
                var done = async();

               async.waterfall([
                 function(cb){
                    if(a==b)
                        // do actual async work
                        myAsyncMethod(cb);
                    else
                      // do sync work
                     return cb();
                }     
              ],
              function(err){
                   return done(err);
              }
             );
          }
        }
```

If the payload of the call executes asynchronously, grunt processes the task correctly.
If the payload of the call executes synchronously, grunt will 'stall', never completing.

**Comment by toddpi314** [comment]
Note: the examples in the README work fine, because they use the setTimeout.

**Comment by toddpi314** [comment]
Looks like the confusion here is that the async delegate doesn't actually return the async callback, but a function that can actualize it.
This is what I was missing:

``` javascript
var done = async();
```

This is kind of confusing. 
Maybe consider just returning the real callback in future versions?

**Comment by Bartvds** [comment]
Sorry for my late reaction, but glad you figured it out.

What makes it confusing is how the module was build with calls that can be switched from sync to async. Current option of switching to async mode (and getting the continuation callback) seems a bit crutchy but of the various methods this is cleanest: 

It doesn't use any magic functionality like switching mode based on the execute function arity (using `Function.length`, like mocha/jasmine test cases do), and neither does it mess with setting function scope (grunt tasks use `var done = this.async();`).
